---

- name: Import mongodb repo key
  apt_key:
    url: "{{ mongo_repo_keyserver }}"
    state: present

- name: Add mongodb repo
  apt_repository:
    filename: "mongodb-3.2"
    mode: 0644
    repo: "{{ mongo_repo_url }}"
    state: present

- name: Install mongodb
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mongodb-org
    - mongodb-org-server
  notify: Restart mongodb

- name: Create mongodb systemd file
  copy:
    src: mongo_systemd
    dest: "{{ mongo_systemd_file }}"
    owner: root
    mode: 0644
  notify: Start mongodb

- name: Configure mongodb
  template:
    src: mongo_config
    dest: /etc/mongod.conf
    mode: 0644
  notify: Restart mongodb
